### ISSUE TITLE
PCSCF failed to start with IPSec

### ISSUE THREAD

**Issue by Stranger-inton** [herlesupreeth/Kamailio_IMS_Config#11]
Hi.

I use IMS setup based on your configs. Kamailio version 5.4.4
I got error by enabling ipsec:

Mar 26 09:01:32 pcscf kamailio: ERROR: <core> [core/cfg.y:3451]: yyparse(): cfg. parser: failed to find command ipsec_destroy_by_contact (params 4)
Mar 26 09:01:32 pcscf kamailio: CRITICAL: <core> [core/cfg.y:3592]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 930, column 130: unknown command, missing loadmodule?

In kamailio source code I did not find cmd ipsec_destroy_by_contact, did you use your own module?

**Comment by herlesupreeth** [comment]
In order use the configs in this repository you need to use the kamailio repo from this link - https://github.com/herlesupreeth/kamailio . In this repo you can find ipsec_destroy_by_contact
