### ISSUE TITLE
hss.web  S-CSCF Name is NULL

### ISSUE THREAD

**Issue by kuanghanqian** [herlesupreeth/Kamailio_IMS_Config#12]
@herlesupreeth ,  
![11](https://user-images.githubusercontent.com/69032320/114006186-cf918600-9892-11eb-8522-f3c3f2ab47dd.png)
I'm configuring HSS.WEB Page, found that S-CSCF name is empty, where does this value come from?

Thank you very much!

**Comment by herlesupreeth** [comment]
@kuanghanqian it will be populated by the Fhoss once the UE registers successfully

**Comment by kuanghanqian** [comment]
OK, Thank you very much!
