### ISSUE TITLE
Separating EPC and IMS on different machines

### ISSUE THREAD

**Issue by BorjanEch0** [herlesupreeth/Kamailio_IMS_Config#15]
I have tried to separate the open5gs core and kamailio ims packages on 2 different machines, but when i do so and try to call an UE i have the problem that caller id is lost and the call goes through as private number?
Do you have any idea what could be causing this? I doubt in 2 things

1. I am forgetting to change some component ip from 127.0.0.x to a lan ip i changed only pcrf.
2. ogstun2 interface is on a different machine and i am using a static route on the ims machine to point all traffic to the epc machine( ip route add 192.168.101.0/24 via 10.0.20.12(EPC) and this causes confusion in the realms or makes the packets have the wrong address.

any ideas would be very helpfull.
If this works i will release a guide and in the near future deb packages for ready setup.

**Comment by BorjanEch0** [comment]
pcscf log
`
98(3331) ERROR: <script>: Preloading NAT-PING. Rows: 0
94(3322) INFO: cdp [authstatemachine.c:741]: Send_ASA(): Send_ASA():  sending ASA
94(3322) ERROR: cdp [routing.c:274]: get_routing_peer(): get_routing_peer(): No connected DefaultRoute peer found for app_id 0 and vendor id 0.
94(3322) ERROR: cdp [diameter_comm.c:142]: AAASendMessage(): AAASendMessage(): Can't find a suitable connected peer in the routing table.
`

**Comment by herlesupreeth** [comment]
@BorjanEch0 Sorry for the late reply. If you could also post the config file I can take a look and help in debugging

**Comment by BorjanEch0** [comment]
no problems! i will send the config files now, which ones do you need? open5gs? kamailio? all?

**Comment by BorjanEch0** [comment]
EPC IP: 10.0.20.12
IMS IP: 10.0.20.13
DNS Server on EPC, set in netplan on both machines.

[bind.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/7511912/bind.zip)
[open5gs.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/7511910/open5gs.zip)
[kamailio_icscf.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/7511911/kamailio_icscf.zip)
