### ISSUE TITLE
Server error on LIR select next S-CSCF

### ISSUE THREAD

**Issue by Dgeka25594** [herlesupreeth/Kamailio_IMS_Config#18]
Hi, herlesupreeth! Again I'm)
I would be grateful if you can help me, I broke my head solving this problem.
Immediately apologize for my English.

I am setting up Kamailio IMS on VirtualBox:
FHоSS 192.168.56.110
PCSCF 192.168.56.112
ICSCF 192.168.56.113
SCSCF 192.168.56.109
 When making a call between sip applications, a call comes to subscriber B and he answers. But subscriber A don't connect.
The dump shows that ICSCF responds with 500 Server error on LIR select next S-CSCF, although it resolves SCSCF and can connect via ports.
Can you tell me what could be the reason?
Dumps  in attache
[scscf.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/7562803/scscf.zip)
[icscf.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/7562804/icscf.zip)
[pcscf.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/7562802/pcscf.zip)

**Comment by herlesupreeth** [comment]
Are those sip clients behind a nat?

**Comment by Dgeka25594** [comment]
Hi. Sorry for the long answer, no, these clients are in the same virtual network of virtual machines.

**Comment by herlesupreeth** [comment]
There is something wrong with PCSCF configuration. As you can see in below picture, the record-route has a route with mo@0.0.0.0

![image](https://user-images.githubusercontent.com/4115839/144394627-f796e80c-9fbd-42e8-83be-27b4bcc4ca9f.png)

**Comment by Dgeka25594** [comment]
Thanks! there was a problem with the network settings.
