### ISSUE TITLE
undefined function in pcscf.cfg

### ISSUE THREAD

**Issue by Cheemer** [herlesupreeth/Kamailio_IMS_Config#2]
when i try to start pcscf i got log:

Jun  5 03:10:04 T3500 kamailio: ERROR: <core> [core/cfg.y:3405]: yyparse(): cfg. parser: failed to find command ipsec_destroy_by_contact (params 4)
Jun  5 03:10:04 T3500 kamailio: CRITICAL: <core> [core/cfg.y:3546]: yyerror_at(): parse error in config file /etc/kamailio_pcscf/kamailio_pcscf.cfg, line 917, column 130: unknown command, missing loadmodule?#012

i have checked this funcion that called ipsec_destroy_by_contact not define in module ims_ipsec_pcscf.

**Comment by herlesupreeth** [comment]
I hope you were able to solve this. If you take the latest commit from my forked kamailio repo it should solve this issue.
