### ISSUE TITLE
High load on Kamailio IMS

### ISSUE THREAD

**Issue by Dgeka25594** [herlesupreeth/Kamailio_IMS_Config#24]
Hi, Herlesupreeth!

The question is not about a problem related to your configuration, so if there is nothing to answer, I will close the ticket, but if you give any advice, I will be grateful.

I set up Kamailio IMS according to your configuration, everything worked out great in the end, and I decided to check how Kamailio copes with the load. I am creating load using sipp application. With a low call generation rate, there are no problems, but if you raise the call generation to more than 20 calls per second, some of the calls fail.
![calls](https://user-images.githubusercontent.com/92918808/161714167-1525a19a-f4a1-4629-9a9e-2edde001dc37.JPG)
I compared the calls and saw that the ICSCF does not send a 180 Ringing message towards the SCSCF.
![bad_call](https://user-images.githubusercontent.com/92918808/161714570-1d2bc1ec-6bf2-4ccc-909b-98b94128207d.JPG)

Below is an example of a successful call.
![good_call](https://user-images.githubusercontent.com/92918808/161714705-30bf71aa-c97b-454a-82a7-e0e32e91eaac.JPG)

CPU, MEM indicators are normal. I increased the shr_mem and pkg_mem parameters.
Any idea where the bug might be? in the logs, I did not find an explicit WAR or ERR on this problem, in SIP messages I also do not see any difference between a successful and unsuccessful call.

10.21.4.226 external IP P-CSCF
10.10.0.1 IP P-CSCF
10.10.0.2 IP S/I-CSCF

[logs.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/8416473/logs.zip)
[dump.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/8416474/dump.zip)

**Comment by herlesupreeth** [comment]
I haven't done load testing so cant say for sure. But from the traces you sent I see the issue in P-CSCF not being able to send out the INVITE to UE. Maybe a TCP issue, not sure

**Comment by Dgeka25594** [comment]
Oh, that's how. And I was sure that the problem is that ICSCF does not send a 180 Ringing message towards the SCSCF (in the screenshot of an unsuccessful call). I want to send a correction, I shot the trace on the node where the I / S-CSCF is located, and the P-CSCF is located on another server. I'll take a trace there too then. Perhaps this is why you decided that the P-CSCF cannot send an INVITE

**Comment by Dgeka25594** [comment]
I was thinking of trying to switch the transport between I-CSCF and S-CSCF to TCP instead of UDP. In addition to the settings on the DNS server, do you still need to make some changes to Kamailio so that it communicates between modules via UDP? (TCP ports Kamailio is already listening)

**Comment by Dgeka25594** [comment]
I think I found a message in the log for the problematic call:

```Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26162]: DEBUG: ims_icscf [scscf_list.c:361]: I_scscf_select(): I_scscf_select() for call-id <43-3057631@10.2.16.63>
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26162]: DEBUG: ims_icscf [scscf_list.c:431]: take_scscf_entry(): Getting scscf entry from list
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26161]: DEBUG: <core> [core/mem/q_malloc.c:482]: qm_free(): qm_free(0x7fe66d684010, 0x7fe66d737b08), called from core: core/parser/parse_via.c: free_via_param_list(2725)
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26160]: DEBUG: <core> [core/mem/q_malloc.c:416]: qm_malloc(): qm_malloc(0x7fe66d684010, 64) returns address 0x7fe66d782a48 frag. 0x7fe66d782a10 (size=64) on 1 -th hit
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26162]: DEBUG: ims_icscf [scscf_list.c:461]: take_scscf_entry(): scscf has not been set so we just look for first match
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26161]: DEBUG: <core> [core/mem/q_malloc.c:525]: qm_free(): freeing frag. 0x7fe66d737ad0 alloc'ed from core: core/parser/parse_via.c: parse_via(2511)
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26162]: DEBUG: ims_icscf [scscf_list.c:368]: I_scscf_select(): no scscf entry for callid [43-3057631@10.2.16.63]```

**Comment by Dgeka25594** [comment]
And depend above, apparently due to the fact that the dialogue was deleted ahead of time, it remains to understand why.
```
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_usrloc_scscf [contact_dlg_handlers.c:129]: contact_dlg_handler(): no dlg out... ignoring!!! for type [4] - usually happens on failure response in dialog
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:1066]: unref_dlg(): unref dlg 0x7fc133ce61d8 with 1 -> 1
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:1066]: unref_dlg(): unref dlg 0x7fc133ce61d8 with 1 -> 0
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:1066]: unref_dlg(): ref <=0 for dialog 0x7fc133ce61d8
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:196]: destroy_dlg(): destroying dialog 0x7fc133ce61d8
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:207]: destroy_dlg(): removed timer for dlg 0x7fc133ce61d8 [3791:1419] with clid '43-3057631@10.2.16.63' and tags '78885556600' 
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:218]: destroy_dlg(): About to run dlg callback for destroy
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_cb.c:277]: run_dlg_callbacks(): dialog=0x7fc133ce61d8, type=8192
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_usrloc_scscf [contact_dlg_handlers.c:129]: contact_dlg_handler(): no dlg out... ignoring!!! for type [8192] - usually happens on failure response in dialog
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:220]: destroy_dlg(): DONE: About to run dlg callback for destroy
Apr  5 08:24:38 ims-core /usr/local/sbin/kamailio[26056]: DEBUG: ims_dialog [dlg_hash.c:156]: destroy_entry_out(): Destroy dialog entry out
```

**Comment by Dgeka25594** [comment]
Can anyone tell me where you can read about the states that Kamailio writes about?
```
DEBUG: ims_dialog [dlg_hash.c:1293]: next_state_dlg(): dialog 0x7fc133ce61d8 changed from state 1 to state 6, due event 4
```
