### ISSUE TITLE
 tel2sip() bug 

### ISSUE THREAD

**Issue by svinson1121** [herlesupreeth/Kamailio_IMS_Config#32]
Hi herlesupreeth,

I'm having an issue I think is related to this tel2sip bug   https://github.com/kamailio/kamailio/issues/1173

in the attached pcap you can see from the PCSCF (10.90.250.50) to the SCSCF (10.90.250.52) the URI is tel:  but from the SCSCF to my asterisk server (10.90.250.100) the URI is sip:  and not formatted correctly because tel2sip() fails.

Asterisk now supports tel: URI's so if I can just stop the SCSCF from converting the URI things should be good, do you know where in the SCSCF cofig the INVITE URI is converted from  tel: to sip:?   

or do you have a solution to the bug referenced?  

Thank you for your time.

 
[scscf-INVITE.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/11143929/scscf-INVITE.zip)

**Comment by herlesupreeth** [comment]
Hi @svinson1121 Can you tell me which branch of kamailio or which kamailio repo you are using? Also, can you provide me logs on SCSCF?
