### ISSUE TITLE
Volte testbed using srsRAN , open5GS , Kamilio IMS  and USRP_B210 

### ISSUE THREAD

**Issue by srinidhikrs** [herlesupreeth/Kamailio_IMS_Config#38]
Hi,

I wanted to test few (audio/video) services (with our Telephony application server)  related to Volte call using Volte testbed based on  srsRAN , open5GS , Kamilio IMS  and USRP_B210 / some other cheaper SDR kit .  So I am planning to setup Volte testbed   in our company's lab following the steps outlined in : https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup

Had few queries on the same :

1)What is the network coverage area (radius) within which handsets would be able to latch on to the LTE signal.?

2)Is Government permission/approval required for such setups in lab ? (India)

3) It seems like programmable sims need to be used and configured for use in handsets available in market . What can be the issues related to the sim compatibility and configuration ?

4)Will i be able to test with any volte compatible handset available in Indian market?

5)Can i just use Kamailio IMS setup without srsRAN to validate call flows using sip client phones in PC? Any references/details related to sip client configurations for connecting to Kamilio IMS would be helpful.

6)Any specific antennas to be used with USRP B210 for testing the volte call flows with handsets available in the market?

7) can srsenb , srsepc, open5gs stack and kamailio IMS run on the same server/laptop?

Any other details related to the same would be helpful .

Thanks
Srinidhi

**Comment by herlesupreeth** [comment]
Hey,

> 1)What is the network coverage area (radius) within which handsets would be able to latch on to the LTE signal.?

With USRP B210 (without antennas) you can get roughly around 2 meters of coverage. With suitable antennas you can achieve around 10 meters of coverage.

> 2)Is Government permission/approval required for such setups in lab ? (India)

When using licensed spectrum it is always required to buy spectrum/get approval from telecom authority of India. But since you are using a USRP B210 and the range is not that far you can use without any permission. If you plan to give any demos using your setup to any officials then I would definitely recommend getting permission/buy spectrum.

> It seems like programmable sims need to be used and configured for use in handsets available in market . What can be the issues related to the sim compatibility and configuration ?

> 4)Will i be able to test with any volte compatible handset available in Indian market?

If you are using programmable SIM cards (e.g. from Sysmocom) you should not have any issues connecting to LTE network you setup. But connecting to IMS is a bit of challenge and varies from handsets to handset, for starters VoLTE option wont be activated in most of the handsets but this can be forcefully activated if you are using Sysmocom USIM/ISIM sim cards

> 5)Can i just use Kamailio IMS setup without srsRAN to validate call flows using sip client phones in PC? Any references/details related to sip client configurations for connecting to Kamilio IMS would be helpful.

yes, you can but you would have to disable Rx interface in P-CSCF configuration files#

> 6)Any specific antennas to be used with USRP B210 for testing the volte call flows with handsets available in the market?

You can use any antennas just ensure its operating frequency is inline with the LTE band you plan to use and also has sufficient gain

> can srsenb , srsepc, open5gs stack and kamailio IMS run on the same server/laptop?

yes it can. Just ensure that server/laptop is powerful enough for example, I have HP EliteBook 655 G9 laptop and its runs all in that machine just fine (NOTE: if you are using open5gs you wont be needing srsepc and srsepc doesnt support VoLTE as far as I know)

I would recommend using this repo for easier deployment - https://github.com/herlesupreeth/docker_open5gs

**Comment by srinidhikrs** [comment]
I am trying to get imsdroid register to pcscf . But failing with 504 server timeout .
PCSCF IP : 192.168.1.28
imsdroid IP : 192.168.1.212

Please help to figure out the reaso for register failure .

I have attached pcap file and pcscf log file
[Uploading pcscflog.zip…]()
[Uploading imsdroid_register.zip…]()

**Comment by herlesupreeth** [comment]
@srinidhikrs you have not uploaded the logs or pcaps correctly. You need to wait until the files gets uploaded and then press on comment button

**Comment by srinidhikrs** [comment]
Attached the logs and pcap file .

Thanks
Srinidhi
________________________________________

**Comment by srinidhikrs** [comment]
Attached the logs and pcap file .

Thanks
Srinidhi
[debug.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/13975338/debug.zip)

**Comment by srinidhikrs** [comment]
First I want to test and validate audio/video service (using Teephony application server) using sip client and IMS+HSS . 
I am to able to start  pcscf , icscf , scscf and hss as per the instructions given in :
https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/

PCSCF , SCSCF , ICSCF are able to load all required modules and start successfully. HSS is also started and running successfully.

When I try to sign-in from imsdroid phone , SIP Register request is sent to PCSCF . PCSCF is processing the incoming REGISTER request and sending 504 timeout with register failure . 

In pcscfg log file I can find the cfgtrace for register request processing. But I am not able find the reason for failure.

IMSdroid runs on different random ports everytime sign-in is attempted but in packet dump pcscf is sending the register request back to imsdroid sip client on port 5060?
Please help to figure out why registration is failing. 

I have caputred and attached proper pcscf.log and also packet dump containing sip requests and responses.

Thanks
Srinidhi
[pcscf.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/13975739/pcscf.zip)

**Comment by herlesupreeth** [comment]
![image](https://github.com/herlesupreeth/Kamailio_IMS_Config/assets/4115839/c80d5c0f-8e4b-4594-b644-c8a7aae9eaca)

This is so wrong, P-CSCF shouldn't be sending SIP REGISTER to UE. Have you made any changes to cfg files of kamailio?

> PCSCF , SCSCF , ICSCF are able to load all required modules and start successfully. HSS is also started and running successfully.

can you elaborate on how you verified this?

**Comment by herlesupreeth** [comment]
aha.. got it. You should not be using IP address in IMSDroid when sending SIP REGISTER. It should be set to sip:ims.mnc001.mcc001.3gppnetwork.org

**Comment by srinidhikrs** [comment]
After changing to sip:ims.mnc001.mcc001.3gppnetwork.org , the registration is filing with HSS user unknown error.

I have attached hss.log , icscf.log , pcap file , screenshots of hss IMPI,IMSU and IMPU page for user alice

icscf is sending UAR request to hss and receiving RC_IMS_DIAMETER_ERROR_USER_UNKNOWN

Please help in finding the reason for error

Th
[hss_user_unknown.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/13976599/hss_user_unknown.zip)
anks
Srinidhi

**Comment by srinidhikrs** [comment]
I created new IMSU , IMPI and IMPU in HSS and selected authentication scheme used by imsdroid . Then I amwas able to register using imsdroid sip client successfully.

Thanks
Srinidhi

**Comment by srinidhikrs** [comment]
I was  able to create service profile and trigger application server routing  with the IMS setup . Now I would like to move to the next step of creating the volte testbed and test the service with android phones available in the market . So I had the following  queries :

1)Is  purchase of  USRP_B210 SDR kit without antennas enough to start with ?

2)For sims do i need to purchase sysmocom usim only (https://shop.sysmocom.de/sysmoISIM-SJA2-SIM-USIM-ISIM-Card-10-pack-with-ADM-keys/sysmoISIM-SJA2-10p-adm) or can the following also be used (https://www.desertcart.in/products/135750554)

3)Any reference to which sim card reader to be purchased to be used for sim programming?

4)After programming sims will there be any compatibility issues with handsets available in Indian market ? (samsung/xiomi/vivo/oneplus/...)

5)Are there any chances of bricking sims/phone during the process?

6)Will there be any frequency /band config changes to be made in srsenb so that india compatible handsets could latch on to the lte signal?

7)Is there any list of COTS UE which are compatible with srsEnb + Open5GS + Kamailio IMS setup ?

Thanks
Srinidhi

**Comment by herlesupreeth** [comment]
> 1)Is purchase of USRP_B210 SDR kit without antennas enough to start with ?

I would recommend buying with antennas because it could happen that you would be using a band used by local operator in the vicinity and it might be interfering so having some extra gain via antennas would be helpful

> 2)For sims do i need to purchase sysmocom usim only (https://shop.sysmocom.de/sysmoISIM-SJA2-SIM-USIM-ISIM-Card-10-pack-with-ADM-keys/sysmoISIM-SJA2-10p-adm) or can the following also be used (https://www.desertcart.in/products/135750554)

I would always recommend Sysmocom ISIM as they are feature rich and is future proof in terms of ability to program any EFs/DFs on the SIM card

> 3)Any reference to which sim card reader to be purchased to be used for sim programming?

Sysmocom also offers SIM card readers such as this - https://shop.sysmocom.de/Omnikey-CardMan-6121-USB-CCID-interface-2FF-sized/cm6121 but you can also get one from Gemalto (I use Gemalto IDBridge K50 Shell Token V3)

> 4)After programming sims will there be any compatibility issues with handsets available in Indian market ? (samsung/xiomi/vivo/oneplus/...)

I dont think so.

> 5)Are there any chances of bricking sims/phone during the process?

Using a programmed SIM wont brick any phone. Rooting your phone may brick your phone.

> 6)Will there be any frequency /band config changes to be made in srsenb so that india compatible handsets could latch on to the lte signal?

This I cannot say for sure. I tried band 7 (dl_earfcn = 3150) and band 20 (dl_earfcn = 6300) and they seems to work

> 7)Is there any list of COTS UE which are compatible with srsEnb + Open5GS + Kamailio IMS setup ?

I dont think there is any official list but these are the phones tested - Mi 9 Pro 5G, Oneplus 5, iPhone X and above, Nokia 5.3

**Comment by srinidhikrs** [comment]
Thanks for the information.  Will ping you if there is any issue in configuring the volte testbed after procurring the required hardware.

**Comment by srinidhikrs** [comment]
I was trying to purchase antennas , usims and simcard reader . Had the following queries :

1)which antenna to be used for VoLTE tesebed along with usrp_b210  SDR kit

Two vert2450-dual-band-antenna-3dbi 
OR
Two VERT900 Vertical Antenna (824-960 MHz, 1710-1990 MHz) Dualband

2)Have placed order for open-cells usim and sim card reader.

3)While trying to sign up  account in sysmocom using the link sent to email, getting error "Unfortunately something went wrong"
and not able to sign up and procure syscmocom usim .

4)Along with sysmocom usim /  open-cells usim can we buy and use Gemalto IDBridge K50 Shell Token V3  (Is it compatible?)

Thanks
Srinidhi

**Comment by herlesupreeth** [comment]
> Two vert2450-dual-band-antenna-3dbi
> OR
> Two VERT900 Vertical Antenna (824-960 MHz, 1710-1990 MHz) Dualband

Depends on what 4G band you want to operate on. If you are planning to use Band 7 then go for Two vert2450-dual-band-antenna-3dbi or if you are planning to use Band 20/3/5 then go for Two VERT900 Vertical Antenna (824-960 MHz, 1710-1990 MHz) Dualband

> 3)While trying to sign up account in sysmocom using the link sent to email, getting error "Unfortunately something went wrong"
> and not able to sign up and procure syscmocom usim .

I would suggest writing them an email - [webshop@sysmocom.de](mailto:webshop@sysmocom.de)

> 4)Along with sysmocom usim / open-cells usim can we buy and use Gemalto IDBridge K50 Shell Token V3 (Is it compatible?)

yes

**Comment by srinidhikrs** [comment]
I have running enb using srsenb, epc using open5gs and ims using kamailio. When i am trying to attach UE to the network , the UE is attaching to the network but IMS registration is not happening. IN connection settings , when Volte option is disabled and enabled  , SIP Register message happens ., but it is failing. Please help in diagnosing the issue.  
Sim : Open-cells USIM
UE : One Plus
[volte_8apr_100.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/14907492/volte_8apr_100.zip)
[epclogs.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/14907534/epclogs.zip)

**Comment by srinidhikrs** [comment]
Hi,

Got One Plus to register to the network with VoLTE. The issue was resolved by adding missing associate imsu for impi and  correcting few config issues.
Looking for one more device (redmi/oppo/vivo/realme) which can attach to the configured network with VoLTE.

Thanks
Srinidhi

**Comment by herlesupreeth** [comment]
> Please check the attached tcpdump and help in resolving the issue
> [volte_call.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/15434296/volte_call.zip)

I see only one of the UE successfully registered with the IMS as result of this call didnt work. Also, the UE which failed to register with IMS apparently lost the connection with eNB so I would check whether your eNB is stable or not.

**Comment by srinidhikrs** [comment]
In the captured tracedump , we can see the following flow
Redmi ---------------INVITE------------->OnePLus
Redmi<--------------183 Session Progress---------OnePLus
Redmi----------------PRACK------------------>OnePLus
Redmi<--------------200 OK(PRACK)-----------OnePlus

S1AP-NAS-EPS : E-RABSetupRequest
S1AP-NAS-EPS : UplinkNASTransport : Ativate Dedicated EPS bearer context reject (Syntactitcal errors in packet filter)

Redmi<---------------480 Temorarily Unavailable---------OnePLus

**Comment by srinidhikrs** [comment]
Based on  the following forum discussion , i have added the required parameter in smf.yaml
https://github.com/open5gs/open5gs/discussions/2712

After that , we were able to make ViLTE (video over LTE) call from redmi phone to OnePLus successfully.

Thanks
Srinidhi
