### ISSUE TITLE
[403] Authentication Failed during SIP registration.

### ISSUE THREAD

**Issue by YokeshwaranM2002** [herlesupreeth/Kamailio_IMS_Config#44]
After Unauthorized - Challenging the UE procedure.Receiving register request from UE, then i am getting  Authentication Failed  message from SCSCF to ICSCF.
[ims_log.zip](https://github.com/user-attachments/files/16330987/ims_log.zip)

**Comment by herlesupreeth** [comment]
![image](https://github.com/user-attachments/assets/44204236-17fd-48bb-97dc-e7af978bde0f)

I think S-CSCF is not connected to HSS correctly and its not able to send SAR diameter request thats why Authentication failed is sent by S-CSCF
