### ISSUE TITLE
VOLTE Call was not established...

### ISSUE THREAD

**Issue by YokeshwaranM2002** [herlesupreeth/Kamailio_IMS_Config#45]
[moto.zip](https://github.com/user-attachments/files/16398311/moto.zip)
when i am trying to call UE2 to UE1 the call procedure is happen, but i am  trying to call UE1 to UE2 "408 time out error" and "500 error on LIR select next SCSCF".below i have attached  call logs from UE1 to UE2 and Message also i am not able to send on both UE's.UE1 is qualcomm chipset and UE2 is Mediatek chipset..

**Comment by herlesupreeth** [comment]
Looks like your phone is sending Media Bearer Loss

![image](https://github.com/user-attachments/assets/a90b8087-b850-4bce-a730-e8e1c8257a8d)

**Comment by YokeshwaranM2002** [comment]
i am getting always 408 error,when i calling from moto g715g mobile to redmi.but,redmi to moto working fine
[moto_ip_log.zip](https://github.com/user-attachments/files/16411627/moto_ip_log.zip)

**Comment by herlesupreeth** [comment]
Are you sure you are using the configuration files from this repository?? Also, which kamailio version are you using??

**Comment by herlesupreeth** [comment]
Please disable the IPSec encryption so that I can debug easily.

**Comment by YokeshwaranM2002** [comment]
> Are you sure you are using the configuration files from this repository?? Also, which kamailio version are you using??

version: kamailio 6.0.0-dev2 (x86_64/linux) 0da3eb
Kamailio_IMS_Config :5.3 version

**Comment by herlesupreeth** [comment]
You have to use the configuration files from the master branch and not 5.3 branch in Kamailio_IMS_Config repo

**Comment by YokeshwaranM2002** [comment]
> You have to use the configuration files from the master branch and not 5.3 branch in Kamailio_IMS_Config repo

ok, i will try with master branch.
[moto.zip](https://github.com/user-attachments/files/16413276/moto.zip)
i have upload the decrypted whireshark file. can you please tell me how to disable the IPSec encryption. and Also can you please tell which branch of kamailio code i need to take..

**Comment by Harsihv** [comment]
can you please tell which branch of kamailio code and rtp engine version is better to take..

**Comment by YokeshwaranM2002** [comment]
When i am trying to enable video call, it is enabling but after 10sec it is disconnecting.
[vc_disconnect.zip](https://github.com/user-attachments/files/17072939/vc_disconnect.zip)

**Comment by herlesupreeth** [comment]
@YokeshwaranM2002 I would suggest retaking the pcap for the following scenario since you have attempted too many calls and hard to debug:

1. Deregister all UEs
2. Start pcap
3. Attach UEs
4. Attempt calling
5. Enable video call
6. Wait for it to fail
7. Stop the pcap

Attach above obtained pcap

**Comment by YokeshwaranM2002** [comment]
[calls.zip](https://github.com/user-attachments/files/17075924/calls.zip)
faced different issues during call.
1. Call not Estabilished
2. Video call not estabilished
3. Call not connecting for long time,getting disconnected in few secs.

**Comment by YokeshwaranM2002** [comment]
[sec_time_call_not_established.zip](https://github.com/user-attachments/files/17088583/sec_time_call_not_established.zip)
Some times when i am trying to call, the call was not established..Sometimes i am getting error as session interval is too small.

**Comment by herlesupreeth** [comment]
Thanks for pcap. In the pcap I see that Redmi is not supporting upgrading audio call to video call

![image](https://github.com/user-attachments/assets/41c299f6-6019-4301-8b05-e2793b1283f8)

![image](https://github.com/user-attachments/assets/eab9ef72-cb4d-452b-bcd8-fb6fbe16e20c)

**Comment by herlesupreeth** [comment]
> Sometimes i am getting error as session interval is too small

For this usually UE updates the session interval time based on the response from other UE but I dont see your Motorola updating the request. Sadly its not upto the IMS to do anything here and upto UE SIP client implementation
