### ISSUE TITLE
During SIP Registration Subscription saved Message is not sending to the UE

### ISSUE THREAD

**Issue by YokeshwaranM2002** [herlesupreeth/Kamailio_IMS_Config#47]
During SIP Registration  200 OK Register and  Subscription saved Message is not received by UE...
[reg_logs.zip](https://github.com/user-attachments/files/16456081/reg_logs.zip)

**Comment by herlesupreeth** [comment]
Can you elaborate on what you mean by those SIP messages not being received by UE?

I see in the pcap that ESP encapsulated SIP messages are sent to the UE IP in ims_ogstun.pcap.

![image](https://github.com/user-attachments/assets/972a1f10-6f5a-4a2e-a796-0504caf82877)

**Comment by mothi-maxeye** [comment]
sorry for the late reply...the above issue is solved..

**Comment by YokeshwaranM2002** [comment]
sorry for the late reply..The issue was solved...

**Comment by YokeshwaranM2002** [comment]
Now i am getting issue in the SMS over IMS
[SMS.zip](https://github.com/user-attachments/files/16594553/SMS.zip)

**Comment by herlesupreeth** [comment]
You have not configured SMSC in your DNS

![image](https://github.com/user-attachments/assets/93f16065-4cec-4c13-8e7e-4f247ff1b98b)

**Comment by YokeshwaranM2002** [comment]
In which file i need to configure for SMSC. Is there any configuration i need to add for sms over ims. i am using open5gs exe.

**Comment by herlesupreeth** [comment]
You need to add DNS entry for SMSC as can be see here - https://github.com/herlesupreeth/docker_open5gs/blob/c5dd48321a18a42abdeb07ee724e73b4ebe6cd28/dns/ims_zone#L27

**Comment by YokeshwaranM2002** [comment]
Still SMS is not working..can you please tell me if anything i have done wrong..Also i have added the SIM configuration details
[ims_logs.zip](https://github.com/user-attachments/files/16633370/ims_logs.zip)

**Comment by YokeshwaranM2002** [comment]
This issue is solved by configure the smsc entity properly.
