### ISSUE TITLE
SMS over IMS ( MT procedure is not happening)

### ISSUE THREAD

**Issue by YokeshwaranM2002** [herlesupreeth/Kamailio_IMS_Config#48]
during the SMS the MO reg procedure is happening, but MT procedure is not happening, UE2 the SMS is not receiving..
[sms_logs.zip](https://github.com/user-attachments/files/16671228/sms_logs.zip)

**Comment by YokeshwaranM2002** [comment]
UE1 IMSI = 405869157933383, MSISDN = 9876543210, SMSP in Sim configuration tool = +9123456789 
UE2 IMSI = 405869157933384, MSISDN = 9876543211, SMSP in Sim configuration tool = +9123456789 
Sending SMS from UE2 to UE1, Message was sent from UE2 to SMSC Entity. After that facing issue..(500 error forwarding to next scscf). Below i have attached the pcap file and Kamailio_smsc.cfg & smsc.cfg files...
[sms_over_ims.zip](https://github.com/user-attachments/files/16678542/sms_over_ims.zip)

**Comment by herlesupreeth** [comment]
Can you try not adding + to the number when you send the SMS?

**Comment by YokeshwaranM2002** [comment]
Without adding  + only i am trying to send sms from (9876543211) to (9876543210) Phone number. 
(+9123456789 ) this number is my SMSP Number configured in the SIM. Can you please tell me [ Kamailio_smsc.cfg and smsc.cfg]  which configuration file i need to use   (/usr/local/src/kamailio/src/modules/smsops/examples/) or (docker_open5gs repo contain file)

**Comment by herlesupreeth** [comment]
I would suggest to use the one in `docker_open5gs`. You need to probably adapt a bit

**Comment by YokeshwaranM2002** [comment]
1) In FHoss i have configured the IMPU service profile as (smsc_sp). It is correct or i need to change as (default_sp).
2) Is mandatory to configure the SMSP in SIM.If it is mandatory which number i need configure.
3) IN MSISDN whether i need to configure phone number With + or not.(eg: +987654321 or 987654321)
4) What could be the reason for getting 500 error forwarding towards next scscf.
5) is this error or waring or info ( [{"message-count":"1","messages":[{"status":"4","error-text":"Bad Credentials"}]}]) getting in smsc entity logs
can you please share me any proven pcap logs and configuration files for sms

**Comment by herlesupreeth** [comment]
> In FHoss i have configured the IMPU service profile as (smsc_sp). It is correct or i need to change as (default_sp)

This is correct

> Is mandatory to configure the SMSP in SIM.If it is mandatory which number i need configure.

No, its not

> IN MSISDN whether i need to configure phone number With + or not.(eg: +987654321 or 987654321)

Without +

> What could be the reason for getting 500 error forwarding towards next scscf

No path to forward the SIP request

> can you please share me any proven pcap logs and configuration files for sms

you can check out the pcap attached here - https://github.com/herlesupreeth/docker_open5gs/issues/286#issuecomment-1974981032 . Even though it over 5G RAN it applies for 4G as well

**Comment by YokeshwaranM2002** [comment]
i have compared the files in docker_open5gs. In that i have noticed dns folder have some difference, Whether it will cause the issue or not, below i have include my bind files.
![docker_bind_folder](https://github.com/user-attachments/assets/f96201c1-4b2c-4810-b150-9369d485e448)

bind.zip](https://github.com/user-attachments/files/16691350/bind.zip)

**Comment by herlesupreeth** [comment]
Aah, I see.. You may also need e164.arpa file in copy that copy and replace IMS_DOMAIN in that file to whatever domain you are using

and need to have the following in your named.conf

```
zone "e164.arpa" {
        type master;
        file "/etc/bind/e164.arpa";
};
```

**Comment by YokeshwaranM2002** [comment]
I have added the file & modified the domain and configured in named.confn but still getting same procedure what i have send you before.
In "e164.arpa" file contain below lines,
[ ; Wildcard to match any tel:+xxxx and change to sip:xxxx@IMS_DOMAIN
* IN NAPTR 10 100 "u" "E2U+sip" "!(^.*$)!sip:\\1@IMS_DOMAIN!" .
* IN NAPTR 20 100 "u" "E2U+sip" "!(^.*$)!sip:+\\1@IMS_DOMAIN!" .  ] 
what is use of this line.i have change the IMS_DOMAIN to my domain as
[ ; Wildcard to match any tel:+xxxx and change to sip:xxxx@IMS_DOMAIN
* IN NAPTR 10 100 "u" "E2U+sip" "!(^.*$)!sip:\\1@ims.mnc869.mcc405.3gppnetwork.org!" .
* IN NAPTR 20 100 "u" "E2U+sip" "!(^.*$)!sip:+\\1@ims.mnc869.mcc405.3gppnetwork.org!" . ] whether i need to change anything in this place (sip:+\\1) [eg: my phone number or SMSP number].

**Comment by herlesupreeth** [comment]
> whether i need to change anything in this place (sip:+\1) [eg: my phone number or SMSP number].

No. It will be automatically be done by regex present there

I would suggest to do retake a pcap with following scenario:

1. Start pcap
2. Register two UEs
3. Send SMS
4. Stop pcap and past here

**Comment by YokeshwaranM2002** [comment]
[smsclogs.zip](https://github.com/user-attachments/files/16707169/smsclogs.zip)

**Comment by herlesupreeth** [comment]
I noticed something wrong in the way Xiaomi is responding to RP-ACK sent from Network to MS

![image](https://github.com/user-attachments/assets/6bd8e60e-2444-4b82-bcaf-6328ca48eff3)

Notice here, that Xiaomi is sending 200 OK without any ESP headers but using IPSec ports. This is wrong implementation in Xiaomi

Can you try putting Xiaomi phone in safemode and rebooting it normally?

**Comment by herlesupreeth** [comment]
Another thing is there is something wrong with your `e164.arpa`, its returning empty response. Please check your DNS configuration and restart the DNS and try clearing DNS cache

![image](https://github.com/user-attachments/assets/f37a3eb8-444e-4f5a-bab9-2e657a158298)

**Comment by herlesupreeth** [comment]
I think you have done some modifications in the below section of kamailio_smscf.cfg which doesnt make sense

```
######################################################################
# SMS Handling
######################################################################
route[SMS] {
#!ifdef WITH_DEBUG
	xlog("SMS-Task\n");
	xlog("-------------------------------------\n");
	xlog("FROM $avp(from)\n");
	xlog("TO   $avp(to)\n");
	xlog("TEXT $avp(text)\n");
	xlog("DCS  $avp(dcs)\n");
#!endif

	# Query ENUM: Local number?
	$var(enum) = "+"+$avp(to);
	if (!enum_pv_query("$var(enum)")) {
		route(SMS_TO_OUTBOUND);
		return $retcode;
	}
	if (sql_query("sms", "insert into messages (caller, callee, text, dcs, valid) values ('$(avp(from){s.escape.common})', '$(avp(to){s.escape.common})', '$(avp(text){s.escape.common})', $avp(dcs), now());"))
		return 1;
	else
		return -1;
}
```

or you have set something in the below param which is incorrect

> modparam("enum", "domain_suffix", "e1234.arpa.")

can you please share your kamailio_smsc.cfg file?

**Comment by YokeshwaranM2002** [comment]
[smsc.zip](https://github.com/user-attachments/files/16709214/smsc.zip)
[dns_files.zip](https://github.com/user-attachments/files/16709666/dns_files.zip)
i have added my bind folder above, i have a doubt whether i need to configure smf-DNS ip address or in Volte ims procedure given(10.4.128.21) ip address

**Comment by herlesupreeth** [comment]
please remove the following line in your kamailio_smsc.cfg and restart SMSC

`modparam("enum", "domain_suffix", "DOMAIN.")`

**Comment by YokeshwaranM2002** [comment]
whether i need to remove this line (modparam("enum", "domain_suffix", "DOMAIN.")) and check or not

**Comment by YokeshwaranM2002** [comment]
![log](https://github.com/user-attachments/assets/9f2d858c-705e-4301-b05b-0b5f1367f7e6)
This is not a problem. Thanks,Now the sms is Working, But in call i am facing issues.The call is disconnecting after 1min.

**Comment by YokeshwaranM2002** [comment]
when i am trying to send SMS through ims getting this error.
![sms](https://github.com/user-attachments/assets/37d372aa-49d0-4a5a-ae4e-3092df976da4)
