### ISSUE TITLE
hi sir, if cscf log show "Diameter: AAR failed on subscription to signalling" , how i can resolve /config it , my packet as attached file

### ISSUE THREAD

**Issue by alf-askey** [herlesupreeth/Kamailio_IMS_Config#7]

**Comment by herlesupreeth** [comment]
there is no pcap attached so cant help

**Comment by herlesupreeth** [comment]
you have configured the pcrf with realm localdomain and not epc.mnc010.mcc001.3gppnetwork.org

![image](https://user-images.githubusercontent.com/4115839/103516535-052c6a80-4e71-11eb-9397-d92eb70856b8.png)

**Comment by alf-askey** [comment]
Thank herlesupreeth to help me . i still have some error as below 

1) when i try to modify realm to "epc.mnc010.mcc001.3gppnetwork.org"  on all conf file ,when launch it show  " [diam] ERROR: ../subprojects/freeDiameter/libfdcore/config.c:457 TLS: The certificate owner does **not match the hostname** 'pcrf.epc.mnc010.mcc001.3gppnetwork.org' " 
[hss.log](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5767437/hss.log)
[mme.log](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5767439/mme.log)
[pcrf.log](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5767440/pcrf.log)
[smf.log](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5767441/smf.log)

2) i modify hostname with domain name as below, but it is still error on  "not match the hostname".
    root@epc:~# hostname
    cn
    root@epc:~# hostname -f
    cn.epc.mnc010.mcc001.3gppnetwork.org
    root@epc:~# dnsdomainname
    epc.mnc010.mcc001.3gppnetwork.org
    root@epc:/etc# domainname
   (none)

3) i use nslookup to search  'pcrf.epc.mnc010.mcc001.3gppnetwork.org' , it response successfully , so could you help me how to do 
root@epc:~# nslookup pcrf.epc.mnc010.mcc001.3gppnetwork.org
Server:         192.188.2.1
Address:        192.188.2.1#53
Name:   pcrf.epc.mnc010.mcc001.3gppnetwork.org
Address: 127.0.0.9

root@epc:/etc/bind# cat epc.mnc010.mcc001.3gppnetwork.org
$ORIGIN epc.mnc010.mcc001.3gppnetwork.org.
$TTL 1W
@                       1D IN SOA       localhost. root.localhost. (
                                        1               ; serial
                                        3H              ; refresh
                                        15M             ; retry
                                        1W              ; expiry
                                        1D )            ; minimum

                           1D IN NS        cn
cn                       1D IN A         192.188.2.1
mme                  1D IN A         127.0.0.2
smf                     1D IN A         127.0.0.4
hss                     1D IN A         127.0.0.8
pcrf                    1D IN A         127.0.0.9

root@epc:/etc/bind# cat ims.mnc010.mcc001.3gppnetwork.org
$ORIGIN ims.mnc010.mcc001.3gppnetwork.org.
$TTL 1W
@                       1D IN SOA       localhost. root.localhost. (
                                        1               ; serial
                                        3H              ; refresh
                                        15M             ; retry
                                        1W              ; expiry
                                        1D )            ; minimum

                        1D IN NS        ns
ns                      1D IN A         192.188.2.1

pcscf                   1D IN A         192.188.2.1
_sip._udp.pcscf         1D SRV 0 0 5060 pcscf
_sip._tcp.pcscf         1D SRV 0 0 5060 pcscf

icscf                   1D IN A         192.188.2.1
_sip._udp               1D SRV 0 0 4060 icscf
_sip._tcp               1D SRV 0 0 4060 icscf

scscf                   1D IN A         192.188.2.1
_sip._udp.scscf         1D SRV 0 0 6060 scscf
_sip._tcp.scscf         1D SRV 0 0 6060 scscf

hss                     1D IN A         192.188.2.1

**Comment by alf-askey** [comment]
> 沒有附加pcap，所以無法幫助

next time , i will do it , thank you

**Comment by alf-askey** [comment]
my  pcrf config as the following,
Identity = "pcrf.epc.mnc010.mcc001.3gppnetwork.org";
Realm = "epc.mnc010.mcc001.3gppnetwork.org";
ListenOn = "127.0.0.9";

TLS_Cred = "/root/open5gs/install/etc/freeDiameter/pcrf.cert.pem", "/root/open5gs/install/etc/freeDiameter/pcrf.key.pem";
TLS_CA = "/root/open5gs/install/etc/freeDiameter/cacert.pem";

LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx" : "0x8888";
LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx";
LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx";
LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx";
LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx";
LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx";
LoadExtension = "/root/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx";

ConnectPeer = "smf.epc.mnc010.mcc001.3gppnetwork.org" { ConnectTo = "127.0.0.4"; No_TLS; };
ConnectPeer = "pcscf.ims.mnc010.mcc001.3gppnetwork.org" { ConnectTo = "192.188.2.1"; No_TLS; Port = 3871; };

**Comment by herlesupreeth** [comment]
As per the guide its recommended to use the following open5gs config files as template and modify just the mnc and mcc and interfaces names as per your setup. https://github.com/herlesupreeth/Open5gs_Config

> when i try to modify realm to "epc.mnc010.mcc001.3gppnetwork.org" on all conf file ,when launch it show " [diam] ERROR: ../subprojects/freeDiameter/libfdcore/config.c:457 TLS: The certificate owner does not match the hostname 'pcrf.epc.mnc010.mcc001.3gppnetwork.org' "

I dont use the freediameter config files but rather put the freediameter settings in the .yaml files itself (refer the config file in above link). This way i dont have to re-generate the certificate every time i change the domain

**Comment by alf-askey** [comment]
thank you , i can launch it over domain name 
i copy config from https://github.com/herlesupreeth/Open5gs_Config to re-config (mme/hss/smf/pcrf) , it can not attach successfully ,
it  show  "Cause: No Suitable Cells In tracking area (15)" , but i check my TAI  , TAI Is ok 

[attach_err_packet.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5769441/attach_err_packet.zip)
[config.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5769442/config.zip)
[log.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5769443/log.zip)

**Comment by herlesupreeth** [comment]
check the mnc and mcc on your eNB, you were using mnc 10 before now you are using mnc 01

**Comment by alf-askey** [comment]
i check ENB (MNC 01) , and it cann establish s1ap with mme , then i check all of mme config about MNC is also  mnc 01
and i also check hss / isim card info. the same is mnc 01 (Does core network  check domain --> epc.mnc010.mcc001.3gppnetwork.org ? )
![s1ap_setup success](https://user-images.githubusercontent.com/67717964/103640406-ea4e1900-4f8a-11eb-8ae9-92477f093c58.jpg)
i check hss database is the same mnc 01
![hss_db](https://user-images.githubusercontent.com/67717964/103640575-339e6880-4f8b-11eb-86c2-15dd5635b707.jpg)
i check sim card is the same  mnc 01
![sim card](https://user-images.githubusercontent.com/67717964/103640621-4ca71980-4f8b-11eb-9869-3183ff4570f7.jpg)

**Comment by herlesupreeth** [comment]
In your logs i see the following 
![image](https://user-images.githubusercontent.com/4115839/103641596-49436c00-4f52-11eb-8426-990acd2b838c.png)

you are using epc.mnc010.mcc010.3gppnetwork.org which corresponds to MCC 010 and MNC 10 which is incorrect for the SIM/eNb you are using (MCC 001 MNC 01)

your realm should be epc.mnc001.mcc001.3gppnetwork.org and NOT epc.mnc010.mcc010.3gppnetwork.org

**Comment by alf-askey** [comment]
thank  herlesupreeth ,  ue attachd successfully 
i will try to modify all config of IMS with "mnc001.mcc001.3gppnetwork.org" tomorrow .

**Comment by alf-askey** [comment]
i follow "https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/" to reinstall IMS, 
When build "dpkg -i ngcp-rtpengine-kernel-dkms_7.4.1.7+0~mr7.4.1.7_all.deb" , it will show 
"Failed to start NGCP RTP/media Proxy Daemon " , i attach install log as attachment
my linux version: Ubuntu 18.04.5 LTS
[ERROR ngcp-rtpengine-kernel-dkms.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5774149/ERROR.ngcp-rtpengine-kernel-dkms.txt)

How to to resolve it ,or do i skip this ? ,use "/usr/sbin/rtpengine --table=1 --interface=192.188.2.1 --listen-ng=127.0.0.1:2223 --tos=184 --pidfile=ngcp-rtpengine-daemon2.pid --no-fallback --foreground"  to launch 

------------------------------

**Comment by herlesupreeth** [comment]
> i follow "https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/" to reinstall IMS,
> When build "dpkg -i ngcp-rtpengine-kernel-dkms_7.4.1.7+0~mr7.4.1.7_all.deb" , it will show
> "Failed to start NGCP RTP/media Proxy Daemon " , i attach install log as attachment
> my linux version: Ubuntu 18.04.5 LTS
> ERROR ngcp-rtpengine-kernel-dkms.txt

That is totally fine. Once you copy the  config file in the next steps and then restart the service it will say active

> 
How to to resolve it ,or do i skip this ? ,use "/usr/sbin/rtpengine --table=1 --interface=192.188.2.1 --listen-ng=127.0.0.1:2223 --tos=184 --pidfile=ngcp-rtpengine-daemon2.pid --no-fallback --foreground" to launch

Not needed

**Comment by alf-askey** [comment]
when  i run "kamailio -f /etc/kamailio_pcscf/kamailio_pcscf.cfg -P /kamailio_pcscf.pid -DD -E -e" , There are som error message as below and attached file ,
...
ERROR: <script>: event_route[htable:mod-init]
ERROR: cdp [receiver.c:688]: receive_loop(): select_recv(): Bad file descriptor
ERROR: <script>: Preloading NAT-PING. Rows: 0

[ERR_kamailio_pcscf.pid_lauch.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5774416/ERR_kamailio_pcscf.pid_lauch.txt)
...

**Comment by herlesupreeth** [comment]
> when i run "kamailio -f /etc/kamailio_pcscf/kamailio_pcscf.cfg -P /kamailio_pcscf.pid -DD -E -e" , There are some error message as below and attached file ,
> ...
> ERROR: <script>: event_route[htable:mod-init]
> ERROR: cdp [receiver.c:688]: receive_loop(): select_recv(): Bad file descriptor
> ERROR: <script>: Preloading NAT-PING. Rows: 0

That is not an error its just a wrong logging level being used in PCSCF

**Comment by alf-askey** [comment]
Thank herlesupreeth , 
(20. Add IMS subscription use in FoHSS as follows from the Web GUI in https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup) to disable barring for impu1

When  i  ue  Mi9 pro 5g UE with IMSI 001010000000011 and MSISDN 0711 to enable Volte , SIP register fail
i check log and package , it show "403 Forbidden - HSS Authorization Rejected" ,then i try to disable barring on IMPU1, it is still fail 
403 reject packet:
[403_forbindden.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5774902/403_forbindden.zip)
log of enable barring:
[403_forbidden_diameter_auth_reject.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5774897/403_forbidden_diameter_auth_reject.txt)
![IMPU-setup](https://user-images.githubusercontent.com/67717964/103752128-4163f480-5044-11eb-805a-b2d12b56d15d.jpg)

disable barring:
![IMPU-setup-2](https://user-images.githubusercontent.com/67717964/103752375-9f90d780-5044-11eb-9a43-41072023e0b5.jpg)

[disable_Barring.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5774925/disable_Barring.zip)

when disable barring 's packet 
[disable_Barring.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5774951/disable_Barring.zip)

![impi](https://user-images.githubusercontent.com/67717964/103753644-432eb780-5046-11eb-97af-6137f310b2e5.jpg)

**Comment by herlesupreeth** [comment]
You may have entered the wrong Ki/OP/OPc value in Fhoss. The phone authorization is rejected due to bad credentials and not due to barring

Send me the details of SIM and screenshots of Fhoss WebUI for this SIM

**Comment by herlesupreeth** [comment]
You have missed executing the below steps

![image](https://user-images.githubusercontent.com/4115839/103756438-a2bda080-500f-11eb-9ccc-8a0280f14485.png)

**Comment by alf-askey** [comment]
sim card info as below , i have add implicit set as below photo
IMSI: 001010000000011
KI: 00112233445566778899AABBCCDDEEFF
OPC: 000102030405060708090A0B0C0D0E0F
IMPI: 001010000000011@ims.mnc001.mcc001.3gppnetwork.org
Domain: ims.mnc001.mcc001.3gppnetwork.org
IMPU1: sip:001010000000011@ims.mnc001.mcc001.3gppnetwork.org
IMPU2: tel:0711
IMPU3: sip:0711
P-CSCF: 192.188.2.1

![phone_1](https://user-images.githubusercontent.com/67717964/103756872-ed104300-504a-11eb-9416-02e9012e96ef.jpg)

![IMSI_config](https://user-images.githubusercontent.com/67717964/103756818-db2ea000-504a-11eb-8500-358e388e45ee.jpg)
![IMPU_1_config](https://user-images.githubusercontent.com/67717964/103756830-dec22700-504a-11eb-912c-8e37a832bd88.jpg)
![IMPU_2_config](https://user-images.githubusercontent.com/67717964/103756832-df5abd80-504a-11eb-9ff5-234ed9b00e15.jpg)
![IMPU_3_config](https://user-images.githubusercontent.com/67717964/103756835-dff35400-504a-11eb-9a3b-3d0a4145e6a8.jpg)

![AMF_SQN](https://user-images.githubusercontent.com/67717964/103757422-b8e95200-504b-11eb-86c0-f788576b2f80.jpg)

**Comment by alf-askey** [comment]
Like this?
![add_implicit](https://user-images.githubusercontent.com/67717964/103758773-9d7f4680-504d-11eb-9744-9b086f2b605d.jpg)

**Comment by herlesupreeth** [comment]
> https://user-images.githubusercontent.com/67717964/103758773-9d7f4680-504d-11eb-9744-9b086f2b605d.jpg

Nope, you need to as above for IMPU sip:001010000000011@ims.mnc001.mcc001.3gppnetwork.org and not for tel:0711

**Comment by alf-askey** [comment]
Am i right or wrong  for below ? it is still register fail
![add_implicit_new](https://user-images.githubusercontent.com/67717964/103759869-4f6b4280-504f-11eb-9379-60cf4450ddad.jpg)

packet :
[after add implicit set packet_new.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5775313/after.add.implicit.set.packet_new.zip)

**Comment by herlesupreeth** [comment]
Its wrong, in this above IMPU area 

1. Goto Add IMPU(s) to Implicit-Set
2. Type tel:0711 and press Add
3. Then, type sip:0711 and press Add
4. Then press Save

**Comment by alf-askey** [comment]
is it right ? , it is still register fail
![add_implicit_action_update](https://user-images.githubusercontent.com/67717964/103762947-18e3f680-5054-11eb-8770-2b26a89c8fe6.jpg)

**Comment by herlesupreeth** [comment]
perfect. the above is correct. Can you send the pic of list of IMPUs as in following screenshot you shared earlier?

https://user-images.githubusercontent.com/67717964/103752375-9f90d780-5044-11eb-9a43-41072023e0b5.jpg

**Comment by alf-askey** [comment]
reg packet :
[sip_reg_fail.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5775563/sip_reg_fail.zip)

**Comment by herlesupreeth** [comment]
Restart the phone and go to Fhoss Web GUI and issue RTR in the IMPI section corresponding to 001010000000011@ims.mnc001.mcc001.3gppnetwork.org

**Comment by alf-askey** [comment]
list of IMPUs
![impu_list](https://user-images.githubusercontent.com/67717964/103765908-e688c800-5058-11eb-81aa-6bc1b723dffe.jpg)

**Comment by alf-askey** [comment]
> Restart the phone and go to Fhoss Web GUI and issue RTR in the IMPI section corresponding to [001010000000011@ims.mnc001.mcc001.3gppnetwork.org](mailto:001010000000011@ims.mnc001.mcc001.3gppnetwork.org) then retry

it is empty for RTR as the below
![RTR-empty](https://user-images.githubusercontent.com/67717964/103766435-cc9bb500-5059-11eb-87bc-7eaba5f28982.jpg)
![RTR-empty-2](https://user-images.githubusercontent.com/67717964/103766507-e76e2980-5059-11eb-8394-f4db6f22d3a9.jpg)

**Comment by alf-askey** [comment]
if i choice opc , op is all zero ? 
![op_opc](https://user-images.githubusercontent.com/67717964/103767283-4e401280-505b-11eb-9f26-7c6f9d8f6505.jpg)

**Comment by herlesupreeth** [comment]
> if i choice opc , op is all zero ?

Correct

> https://user-images.githubusercontent.com/67717964/103766435-cc9bb500-5059-11eb-87bc-7eaba5f28982.jpg

In this menu, its fine even if its empty. select "Removed S-CSCF" from Reason Dropdown menu and press RTR-All

**Comment by alf-askey** [comment]
thank  herlesupreeth , 

my phone 1 (ASUS  zone phone) , phone 2( Mi9 pro 5g) it can register to IMS successfully ,
but phone 2 call phone 1 or phone 1 call phone 2 , it is failure , packet as the below
[invite fail.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5779409/invite.fail.zip)

![phone1-phone2_SIP_reg_success](https://user-images.githubusercontent.com/67717964/103847925-33fa4900-50dc-11eb-9838-16160f4c9d77.jpg)

**Comment by herlesupreeth** [comment]
I don't see sip:0711 and sip:0713 IMPUs in the above screenshot? It must be there for successful call. Please dont skip steps in the guide

**Comment by alf-askey** [comment]
thank you ,i add sip:0711 ,sip:0713 into IMPU ,there is no the above error, but now phone 2 call phone 1 it show "Status-Line: SIP/2.0 580 Precondition Failure" as the below packet
[code_580 fail.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5779624/code_580.fail.zip)
![add_sip 0711_sip 0713](https://user-images.githubusercontent.com/67717964/103851973-ef73ab00-50e5-11eb-83bc-92cd8d9d6905.jpg)

**Comment by alf-askey** [comment]
[ERR_LOG.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5779746/ERR_LOG.txt)
This is error message 
107(2405) ERROR: ims_qos [ims_qos_mod.c:935]: w_rx_aar(): No P-Called-Party hdr found in response. Using req URI from dlg - we shouldn't have to do this107(2405              ) INFO: cdp [authstatemachine.c:270]: auth_client_statefull_sm_process(): after               callback of event 1
...
98(2396) ERROR: <script>: OPTIONS to sip:10.45.1.3:8901 via sip:10.45.1.3:8901;transport=tcp...
98(2396) ERROR: <script>: OPTIONS to sip:c294aa78-c5df-4cfa-a615-6401d91ae569@10.45.1.2:41190 via sip:10.45.1.2:41190;transport=tcp...
106(2404) ERROR: <script>: request sent to sip:c294aa78-c5df-4cfa-a615-6401d91ae569@10.45.1.2:41190 completed with code: 200, Type 1
107(2405) ERROR: <script>: request sent to sip:10.45.1.3:8901 completed with code: 200, Type 1

**Comment by alf-askey** [comment]
when phone 2(tel:0713) call self (0713) , package is show "Status-Line: SIP/2.0 486 Busy Here"

when phone 2(tel:0711) call self (0711) , package is show "Status-Line: SIP/2.0 500 Server error on LIR select next S-CSCF" 
why is different ?

[call_self.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5779917/call_self.zip)

**Comment by herlesupreeth** [comment]
The pcap you attached does not have all the packets. I would suggest to do the following

1. Restart PCSCF, SCSCF, ICSCF
2. Take packet capture with interface any and NO capture filters

Then, send me that packet capture.

**Comment by herlesupreeth** [comment]
Btw, which eNb are you using?

**Comment by alf-askey** [comment]
1,) i restart  open5gs and IMS , then restart phone 1 and 2  and from phone 1 call phone 2 , phone 2 call phone 1 ,the packet as below
[phone1_phone 2_fail.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5780909/phone1_phone.2_fail.zip)
2) my eNB is  eNB(smallcell) of (askey computer corp)

**Comment by alf-askey** [comment]
I change eNB to eNB of amarisoft , the packet as the below and same failure
[amarisoft_eNB-phone1_phone 2_fail.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5781066/amarisoft_eNB-phone1_phone.2_fail.zip)

**Comment by herlesupreeth** [comment]
Okay, thanks a lot for trying it out. I will get back to you soon if I find anything

**Comment by herlesupreeth** [comment]
Are you sure you are using the latest changes in Kamalio_IMS_Config repository? I remember fixing this issue

**Comment by alf-askey** [comment]
how to update the latest changes in Kamalio_IMS_Config , could you teach me ,  
Is it possible not to reinstall ? 
i use "git checkout -b 5.3 origin/5.3"

**Comment by alf-askey** [comment]
git checkout -b 5.4 origin/5.4  , this  one is ok ?

**Comment by herlesupreeth** [comment]
> Is it possible not to reinstall ?
> i use "git checkout -b 5.3 origin/5.3"

Not kamailio source code but just the configuration files

> do i just do step 4~ step 8 base on https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/ ?

No, only step 14 but change the IP addresses as per your setup

**Comment by herlesupreeth** [comment]
Can you try once more the calling and send me pcap and the logs of PCSCF?

**Comment by alf-askey** [comment]
i go to https://www.kamailio.org/w/download/ , i just find "kamailio.cfg" and "sip-router.cfg" ,  it cannot find all config 

Can you try once more the calling and send me pcap and the logs of PCSCF?  
---> Sure ,wait me a moent

**Comment by alf-askey** [comment]
pcscf packet and log as the below
[packet.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5781556/packet.zip)
[pcscf_log.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5781557/pcscf_log.txt)

**Comment by alf-askey** [comment]
git clone https://github.com/herlesupreeth/Kamailio_IMS_Config --> is it latest config ? 
or where i can find it from other web site or kamailio offical site

**Comment by alf-askey** [comment]
do i need load module : ip_conntrack_sip / ip_nat_sip  ?

**Comment by alf-askey** [comment]
hi herlesupreeth,  i found(phone 1 tel:0-711) have issue "Status-Line: SIP/2.0 500 Server error on LIR select next S-CSCF"
how to resolve it ? 
packet:
[code-500_server error.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5785331/code-500_server.error.zip)

**Comment by herlesupreeth** [comment]
> git clone https://github.com/herlesupreeth/Kamailio_IMS_Config --> is it latest config ?

These are only config you need to take. Btw, I pushed some more changes today. Please take them adapt to your settings and re-try (send me logs and pcap in case of issue)

> hi herlesupreeth, i found(phone 1 tel:0-711) have issue "Status-Line: SIP/2.0 500 Server error on LIR select next S-CSCF"
> how to resolve it ?
> packet:

From the looks of it, the UE with tel:0713 is not registered or got de-registered from the IMS

**Comment by alf-askey** [comment]
i use new config to setup and phone 1 call phone 2 , phone 2 call phone 1 , it show " Status-Line: SIP/2.0 500 Server Internal Error" 
-------------
[new_config_packet.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5793861/new_config_packet.zip)
[fhohss_log.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5793863/fhohss_log.txt)
[icscf_log.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5793864/icscf_log.txt)
[open5gs_log.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5793865/open5gs_log.txt)
[pcscf_log.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5793866/pcscf_log.txt)
[scscf_log.txt](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5793867/scscf_log.txt)

**Comment by alf-askey** [comment]
hi Herlesupreeth,
if i am use "ISIM" ,is not "USIM" ,is this ok ?

**Comment by herlesupreeth** [comment]
ISIM is not required, it works with USIM itself

**Comment by herlesupreeth** [comment]
Please close this issue if you have resolved this issue.

**Comment by Arunkumar130** [comment]
> thank you , i can launch it over domain name i copy config from https://github.com/herlesupreeth/Open5gs_Config to re-config (mme/hss/smf/pcrf) , it can not attach successfully , it show "Cause: No Suitable Cells In tracking area (15)" , but i check my TAI , TAI Is ok
> 
> [attach_err_packet.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5769441/attach_err_packet.zip) [config.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5769442/config.zip) [log.zip](https://github.com/herlesupreeth/Kamailio_IMS_Config/files/5769443/log.zip)

I am also Facing this issue.can you please tell how to solve that.
